language: node_js
node_js:
  - "7"
branches:
  only:
    - master
  except:
    - develop
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
